import React, {useMemo, useState} from 'react';
import {RotateCcw, X} from 'lucide-react';
import {ArrayModel, EquivalentFractionModel, FractionComparison, FractionNumberLine, MeasurementModel, NumberLineModel, PlaceValueModel, type FractionValue} from './visual-models';
import './maths-lab.css';
import './visual-models.css';

export type LabTool = 'fractions'|'percentages'|'number-line'|'place-value'|'arrays'|'clock'|'grid'|'measurement';

const TOOLS:{id:LabTool;label:string;icon:string}[]=[
  {id:'fractions',label:'Fractions',icon:'◒'}, {id:'percentages',label:'Percentages',icon:'%'},
  {id:'number-line',label:'Number line',icon:'↔'}, {id:'place-value',label:'Place value',icon:'123'},
  {id:'arrays',label:'Arrays',icon:'⠿'}, {id:'clock',label:'Clock',icon:'◷'},
  {id:'grid',label:'Grid',icon:'▦'}, {id:'measurement',label:'Measurement',icon:'⌇'},
];

export function recommendedLabTool(question:any):LabTool{
  const recommended=String(question?.payload?.visual_mathematics?.recommended_model||question?.payload?.recommended_model||'') as LabTool;
  if(TOOLS.some(tool=>tool.id===recommended))return recommended;
  const skill=String(question?.skill||'').toLowerCase(),topic=String(question?.topic||'').toLowerCase(),prompt=String(question?.prompt||'').toLowerCase();
  if(skill.includes('fraction'))return'fractions'; if(skill.includes('percent'))return'percentages';
  if(skill.includes('clock')||skill.includes('duration')||prompt.includes('time'))return'clock';
  if(skill.includes('grid')||skill.includes('coordinate')||topic==='space')return'grid';
  if(skill.includes('place')||skill.includes('written_'))return'place-value';
  if(skill.includes('multiplication')||skill.includes('division')||skill.includes('fact_recall'))return'arrays';
  if(topic==='measurement')return'measurement'; return'number-line';
}

export function MathsLab({question,onClose}:{question:any;onClose:()=>void}){
  const suggested=useMemo(()=>recommendedLabTool(question),[question]);
  const[tool,setTool]=useState<LabTool>(suggested),[resetKey,setResetKey]=useState(0),[support,setSupport]=useState<'why'|'another'|null>(null);
  const strategies=question?.payload?.solution_strategies||[];
  const[strategyIndex,setStrategyIndex]=useState(0);
  const strategy=strategies[strategyIndex%Math.max(1,strategies.length)];
  return <div className="lab-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}>
    <section className="maths-lab" role="dialog" aria-modal="true" aria-labelledby="maths-lab-title">
      <header className="lab-header"><div><small>INTERACTIVE MATHS LAB</small><h2 id="maths-lab-title">Build it, move it, explain it</h2><p>Use manipulatives to explore the method. The lab never submits or fills the assessed answer.</p></div><button type="button" aria-label="Close maths lab" onClick={onClose}><X/></button></header>
      <div className="lab-layout"><nav className="lab-tabs" aria-label="Maths lab tools">{TOOLS.map(item=><button type="button" key={item.id} className={tool===item.id?'selected':''} aria-pressed={tool===item.id} onClick={()=>{setTool(item.id);setResetKey(v=>v+1)}}><span>{item.icon}</span>{item.label}{item.id===suggested&&<small>Suggested</small>}</button>)}</nav>
        <div className="lab-workspace"><div className="lab-workspace-head"><div><small>CURRENT MODEL</small><b>{TOOLS.find(item=>item.id===tool)?.label}</b></div><div className="lab-support-actions"><button type="button" aria-pressed={support==='why'} onClick={()=>setSupport(v=>v==='why'?null:'why')}>Why?</button><button type="button" aria-pressed={support==='another'} onClick={()=>{setSupport('another');if(strategies.length)setStrategyIndex(i=>(i+1)%strategies.length)}}>Show another way</button><button type="button" onClick={()=>{setResetKey(v=>v+1);setSupport(null)}}><RotateCcw size={17}/> Start over</button></div></div>{support&&<aside className="lab-support" role="status"><b>{support==='why'?'Why this model helps':strategy?.title||'Another strategy to try'}</b><p>{support==='another'&&strategy?.explanation?strategy.explanation:supportText(tool,support)}</p></aside>}<LabModel key={`${tool}-${resetKey}`} tool={tool}/></div>
      </div>
    </section>
  </div>;
}

function supportText(tool:LabTool,mode:'why'|'another'){
  const guidance:Record<LabTool,[string,string]>={fractions:['Equal-sized wholes let you compare the shaded amounts fairly.','Rename both fractions with matching partitions or place both on one number line.'],percentages:['The bar, fraction, decimal and quantity describe the same part of one whole.','Use benchmark percentages, then combine benchmark parts.'],'number-line':['The jumps show the same changes made in the calculation.','Bridge through a friendly number, then make the remaining jump.'],'place-value':['Aligned columns keep each digit in its correct place.','Partition by place, calculate matching parts, then recombine.'],arrays:['Equal rows show factors, groups and total together.','Partition a factor or use the inverse multiplication relationship.'],clock:['The hands and elapsed-time jumps describe the same time change.','Jump to a nearby hour, then add the remaining minutes.'],grid:['Axes define the position without writing the assessed reference in the square.','Trace the two labels until their paths meet.'],measurement:['A scale links the physical length to the selected unit.','Compare units or partition the measurement into known lengths.']};
  return guidance[tool][mode==='why'?0:1];
}

function LabModel({tool}:{tool:LabTool}){if(tool==='fractions')return <FractionLab/>;if(tool==='percentages')return <PercentageLab/>;if(tool==='number-line')return <NumberLineLab/>;if(tool==='place-value')return <PlaceValueLab/>;if(tool==='arrays')return <ArrayLab/>;if(tool==='clock')return <ClockLab/>;if(tool==='grid')return <GridLab/>;return <MeasurementLab/>}

function FractionLab(){const[items,setItems]=useState<FractionValue[]>([{label:'First fraction',numerator:3,denominator:4},{label:'Second fraction',numerator:5,denominator:8}]);const[view,setView]=useState<'bars'|'number-line'|'equivalent'>('bars');return <div className="lab-model"><p>Both fractions use the same whole width. Change the parts and switch representations to inspect the same relationship.</p><div className="lab-jumps" role="group" aria-label="Fraction representation"><button type="button" aria-pressed={view==='bars'} onClick={()=>setView('bars')}>Fraction bars</button><button type="button" aria-pressed={view==='number-line'} onClick={()=>setView('number-line')}>Number line</button><button type="button" aria-pressed={view==='equivalent'} onClick={()=>setView('equivalent')}>Equivalent fractions</button></div>{view==='bars'&&<FractionComparison items={items} interactive onChange={setItems}/>} {view==='number-line'&&<FractionNumberLine values={items}/>} {view==='equivalent'&&<EquivalentFractionModel value={items[0]}/>}<output>{items[0].numerator/items[0].denominator===items[1].numerator/items[1].denominator?'The fractions are equivalent.':items[0].numerator/items[0].denominator>items[1].numerator/items[1].denominator?'The first fraction is larger.':'The second fraction is larger.'}</output></div>}
function PercentageLab(){const[value,setValue]=useState(25),[quantity,setQuantity]=useState(100),divisor=gcd(value,100);return <div className="lab-model"><p>Move the percentage and watch fraction, decimal and quantity stay synchronised.</p><label>Percentage: <b>{value}%</b><input aria-label="Percentage" type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)}/></label><div className="lab-percent-bar" aria-label={`${value} percent shaded`}><i style={{width:`${value}%`}}/></div><div className="lab-linked-values"><span><small>Fraction</small><b>{value/divisor}/{100/divisor}</b></span><span><small>Decimal</small><b>{(value/100).toFixed(2)}</b></span><span><small>Of quantity</small><b>{format(value/100*quantity)}</b></span></div><label>Whole quantity<input aria-label="Whole quantity" type="number" min="1" value={quantity} onChange={e=>setQuantity(Math.max(1,+e.target.value))}/></label></div>}
function NumberLineLab(){const[min,setMin]=useState(0),[max,setMax]=useState(100),[value,setValue]=useState(30);return <div className="lab-model"><p>Move the marker or make jumps. The marker and written value remain synchronised.</p><div className="lab-range-inputs"><label>Start<input aria-label="Number line start" type="number" value={min} onChange={e=>setMin(+e.target.value)}/></label><label>End<input aria-label="Number line end" type="number" value={max} onChange={e=>setMax(Math.max(min+1,+e.target.value))}/></label></div><NumberLineModel min={min} max={max} value={value} onChange={setValue}/><div className="lab-jumps">{[-10,-1,1,10].map(j=><button type="button" key={j} onClick={()=>setValue(v=>Math.max(min,Math.min(max,v+j)))}>{j>0?'+':''}{j}</button>)}</div></div>}
function PlaceValueLab(){const[value,setValue]=useState(243);return <div className="lab-model"><p>Change the number and inspect the same value by place.</p><label>Number<input aria-label="Place value number" type="number" min="0" max="9999" value={value} onChange={e=>setValue(Math.max(0,Math.min(9999,+e.target.value)))}/></label><PlaceValueModel value={value}/><div className="lab-jumps"><button type="button" onClick={()=>setValue(v=>Math.max(0,v-10))}>− 1 ten</button><button type="button" onClick={()=>setValue(v=>Math.min(9999,v+10))}>+ 1 ten</button><button type="button" onClick={()=>setValue(v=>Math.max(0,v-100))}>− 1 hundred</button><button type="button" onClick={()=>setValue(v=>Math.min(9999,v+100))}>+ 1 hundred</button></div></div>}
function ArrayLab(){const[rows,setRows]=useState(3),[columns,setColumns]=useState(4);return <div className="lab-model"><p>Build equal groups to model multiplication or division.</p><div className="lab-range-inputs"><label>Rows<input aria-label="Array rows" type="number" min="1" max="12" value={rows} onChange={e=>setRows(Math.max(1,Math.min(12,+e.target.value)))}/></label><label>Columns<input aria-label="Array columns" type="number" min="1" max="12" value={columns} onChange={e=>setColumns(Math.max(1,Math.min(12,+e.target.value)))}/></label></div><ArrayModel rows={rows} columns={columns}/></div>}
function ClockLab(){const[hour,setHour]=useState(3),[minute,setMinute]=useState(20),minuteAngle=minute*6,hourAngle=(hour%12)*30+minute*.5;return <div className="lab-model"><p>Move the hands and connect the analogue and digital time.</p><div className="lab-clock"><b className="n12">12</b><b className="n3">3</b><b className="n6">6</b><b className="n9">9</b><i className="hour" style={{transform:`rotate(${hourAngle}deg)`}}/><i className="minute" style={{transform:`rotate(${minuteAngle}deg)`}}/><span/></div><output>{hour}:{String(minute).padStart(2,'0')}</output><label>Hour<input aria-label="Clock hour" type="range" min="1" max="12" value={hour} onChange={e=>setHour(+e.target.value)}/></label><label>Minutes<input aria-label="Clock minutes" type="range" min="0" max="55" step="5" value={minute} onChange={e=>setMinute(+e.target.value)}/></label></div>}
function GridLab(){const[selected,setSelected]=useState('B3'),rows=['A','B','C','D'],columns=[1,2,3,4];return <div className="lab-model"><p>Select a square and practise reading the two axes.</p><div className="lab-grid" style={{gridTemplateColumns:`auto repeat(${columns.length},1fr)`}}><span/>{columns.map(c=><b key={c}>{c}</b>)}{rows.flatMap(r=>[<b key={`${r}-label`}>{r}</b>,...columns.map(c=>{const ref=`${r}${c}`;return <button aria-label={`Grid square ${ref}`} type="button" className={selected===ref?'selected':''} key={ref} onClick={()=>setSelected(ref)}/>})])}</div><output>Selected reference: {selected}</output></div>}
function MeasurementLab(){const[length,setLength]=useState(8),[width,setWidth]=useState(3);return <div className="lab-model"><p>Adjust dimensions and connect the diagram to the measured values.</p><div className="lab-range-inputs"><label>Length (cm)<input aria-label="Rectangle length" type="number" min="1" max="20" value={length} onChange={e=>setLength(Math.max(1,Math.min(20,+e.target.value)))}/></label><label>Width (cm)<input aria-label="Rectangle width" type="number" min="1" max="20" value={width} onChange={e=>setWidth(Math.max(1,Math.min(20,+e.target.value)))}/></label></div><MeasurementModel length={length} width={width}/></div>}
function gcd(a:number,b:number):number{return b===0?Math.max(1,a):gcd(b,a%b)}function format(value:number){return Number.isInteger(value)?String(value):value.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
