import './v0100.css';

const API='api';
function h():Record<string,string>{const x:Record<string,string>={'Content-Type':'application/json'};const t=localStorage.getItem('token');if(t)x.Authorization=`Bearer ${t}`;return x}
async function get(p:string){const r=await fetch(API+p,{headers:h()});return r.ok?r.json():null}
async function put(p:string,b:any){const r=await fetch(API+p,{method:'PUT',headers:h(),body:JSON.stringify(b)});return r.ok?r.json():null}
function q(){const w=(window as any).__mq_ws;return w?.questions?.find((x:any)=>x.id===w.current_question_id)}

function speak(text:string,visual?:string){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(visual?`${text}. ${visual}`:text);u.lang='en-AU';u.rate=.92;speechSynthesis.speak(u)}

function renderManipulative(d:any){if(d.type==='fraction_tiles')return `<div class="mq-manip tray" data-tray>${d.pieces.map((n:number)=>`<button draggable="true" data-piece="1/${n}">1/${n}</button>`).join('')}<div class="dropzone">Drop fraction pieces here</div></div>`;if(d.type==='place_value')return `<div class="mq-manip place">${d.columns.map((c:string)=>`<div data-col="${c}"><b>${c}</b><button draggable="true" data-piece="▉">▉</button></div>`).join('')}</div>`;if(d.type==='ruler')return `<div class="mq-manip ruler">${Array.from({length:d.length+1},(_,i)=>`<span>${i}</span>`).join('')}<input type="range" min="0" max="${d.length}" value="0"></div>`;if(d.type==='grid_tokens')return `<div class="mq-manip gridtokens">${d.columns.flatMap((c:string)=>Array.from({length:d.rows},(_,i)=>`<button data-cell="${c}${i+1}">${c}${i+1}</button>`)).join('')}</div>`;return `<div class="mq-manip counters">${Array.from({length:d.count},()=>'<button draggable="true">●</button>').join('')}<div class="dropzone">Group counters here</div></div>`}

async function tools(){const card=document.querySelector('.question-card');const cur=q();if(!card||!cur||card.querySelector('.mq-v0100-tools'))return;const bar=document.createElement('div');bar.className='mq-v0100-tools';bar.innerHTML='<button data-read>🔊 Read aloud</button><button data-scratch>✏️ Scratchpad</button><button data-manip>🧩 Maths tools</button>';card.querySelector('h1')?.insertAdjacentElement('beforebegin',bar);
bar.querySelector('[data-read]')?.addEventListener('click',async()=>{const d=await get(`/questions/${cur.id}/read-aloud`);if(d)speak(d.text,d.visual_description)});
bar.querySelector('[data-scratch]')?.addEventListener('click',async()=>{let p=card.querySelector('.mq-scratch') as HTMLElement|null;if(p){p.remove();return}const d=await get(`/questions/${cur.id}/scratchpad`);p=document.createElement('div');p.className='mq-scratch';p.innerHTML=`<div><b>Scratchpad</b><small>Use this for working out. It does not affect your score.</small></div><textarea placeholder="Write your working here...">${d?.content||''}</textarea><button>Save working</button>`;card.querySelector('.mq-v0100-tools')?.insertAdjacentElement('afterend',p);p.querySelector('button')?.addEventListener('click',async()=>{await put(`/questions/${cur.id}/scratchpad`,{content:(p!.querySelector('textarea') as HTMLTextAreaElement).value});(p!.querySelector('button') as HTMLButtonElement).textContent='Saved ✓'})});
bar.querySelector('[data-manip]')?.addEventListener('click',async()=>{let p=card.querySelector('.mq-manip-panel') as HTMLElement|null;if(p){p.remove();return}const d=await get(`/questions/${cur.id}/manipulative`);if(!d)return;p=document.createElement('div');p.className='mq-manip-panel';p.innerHTML=`<div><b>Interactive maths tools</b><small>${d.instruction}</small></div>${renderManipulative(d)}`;card.querySelector('.mq-v0100-tools')?.insertAdjacentElement('afterend',p);let dragged='';p.querySelectorAll('[draggable]').forEach((e:any)=>e.addEventListener('dragstart',()=>dragged=e.dataset.piece||e.textContent));p.querySelectorAll('.dropzone,[data-col]').forEach((z:any)=>{z.addEventListener('dragover',(e:DragEvent)=>e.preventDefault());z.addEventListener('drop',(e:DragEvent)=>{e.preventDefault();const s=document.createElement('span');s.textContent=dragged;z.append(s)})})})}

async function weekly(){const page=document.querySelector('.page');if(!page||page.querySelector('.mq-weekly')||!document.body.textContent?.includes('Parent controls'))return;const d=await get('/reports/weekly');if(!d)return;const s=document.createElement('section');s.className='panel mq-weekly';s.innerHTML=`<div class="mq-weekly-head"><div><p class="eyebrow">WEEKLY LEARNING REPORT</p><h2>${d.period.start} to ${d.period.end}</h2></div><span>v0.10</span></div><p class="summary">${d.parent_summary}</p><div class="mq-weekly-stats"><article><strong>${d.days_completed}</strong><small>learning days</small></article><article><strong>${d.questions_attempted}</strong><small>questions</small></article><article><strong>${d.first_attempt_accuracy}%</strong><small>first-attempt accuracy</small></article><article><strong>${d.hints_used}</strong><small>hints</small></article></div><div class="mq-weekly-cols"><div><h3>Strongest evidence</h3>${d.strongest_skills.map((x:any)=>`<p><b>${x.title}</b><span>${x.mastery}% mastery</span></p>`).join('')||'<p>No mastery evidence yet.</p>'}</div><div><h3>Useful next focus</h3>${d.skills_to_support.map((x:any)=>`<p><b>${x.title}</b><span>${x.mastery}% mastery</span></p>`).join('')||'<p>No priority support area this week.</p>'}</div></div>`;page.prepend(s)}
function version(){document.querySelectorAll('.version').forEach(n=>n.textContent='Version 0.10.0');document.querySelectorAll('.header-version').forEach(n=>n.textContent='v0.10.0')}
function enhance(){version();tools();weekly()}
new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});enhance();
