import './v080.css';
import {fractionComparisonMarkup, gridReferenceMarkup} from './visual-markup';

const API='api';
function authHeaders():Record<string,string>{const h:Record<string,string>={};const token=localStorage.getItem('token');if(token)h.Authorization=`Bearer ${token}`;return h}
async function get(path:string){const r=await fetch(API+path,{headers:authHeaders()});return r.ok?r.json():null}
async function post(path:string,body:any){const r=await fetch(API+path,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Request failed'}))).detail||'Request failed');return r.json()}

function visualMarkup(v:any){if(!v)return'';if(v.type==='fraction_compare')return fractionComparisonMarkup(v.items);if(v.type==='number_line')return `<div class="mq-visual number-line"><div class="line-track">${Array.from({length:v.steps+1},(_,i)=>`<button type="button" data-visual-answer="${i}"><i></i><span>${i===0?'0':i===v.steps?'1':''}</span></button>`).join('')}</div></div>`;if(v.type==='clock'){const mh=v.minute*6,hh=(v.hour%12)*30+v.minute*.5;return `<div class="mq-visual clock"><div class="clock-face"><i class="hour" style="transform:rotate(${hh}deg)"></i><i class="minute" style="transform:rotate(${mh}deg)"></i><b>12</b><b>3</b><b>6</b><b>9</b></div></div>`}if(v.type==='angle')return `<div class="mq-visual angle"><svg viewBox="0 0 240 150"><line x1="60" y1="120" x2="195" y2="120"/><line x1="60" y1="120" x2="${60+110*Math.cos(v.degrees*Math.PI/180)}" y2="${120-110*Math.sin(v.degrees*Math.PI/180)}"/><path d="M90 120 A30 30 0 0 0 ${60+30*Math.cos(v.degrees*Math.PI/180)} ${120-30*Math.sin(v.degrees*Math.PI/180)}"/></svg></div>`;if(v.type==='bar_chart'){const m=Math.max(...v.values);return `<div class="mq-visual bar-chart">${v.labels.map((x:string,i:number)=>`<div><span style="height:${Math.max(12,v.values[i]/m*120)}px"></span><b>${v.values[i]}</b><small>${x}</small></div>`).join('')}</div>`}if(v.type==='grid')return gridReferenceMarkup(v);return''}

const originalFetch=window.fetch.bind(window);window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const r=await originalFetch(input,init);try{const u=String(input);if(u.endsWith('/api/worksheets/today')&&r.headers.get('content-type')?.includes('json')){const data=await r.clone().json();(window as any).__mq_ws=data;setTimeout(renderVisualForCurrent,0)}}catch{}return r};

function renderVisualForCurrent(){const card=document.querySelector('.question-card');if(!card)return;const ws=(window as any).__mq_ws;const q=ws?.questions?.find((x:any)=>x.id===ws.current_question_id);const v=q?.payload?.visual;const existing=card.querySelector('.mq-v080-visual') as HTMLElement|null;if(!v){existing?.remove();return}if(existing?.dataset.qid===String(q.id))return;existing?.remove();const holder=document.createElement('div');holder.className='mq-v080-visual';holder.dataset.qid=String(q.id);holder.innerHTML=visualMarkup(v);const answer=card.querySelector('.answer');(answer||card.querySelector('h1'))?.insertAdjacentElement('beforebegin',holder);holder.querySelectorAll('[data-visual-answer]').forEach((el:any)=>el.addEventListener('click',()=>{const value=el.dataset.visualAnswer;const choices=Array.from(card.querySelectorAll('button.choice')) as HTMLButtonElement[];const matching=choices.find(b=>(b.textContent||'').trim()===value);matching?.click()}))}

let parentLoading=false,studentLoading=false;
async function enhanceParentAssignments(){const page=document.querySelector('.page');if(parentLoading||!page||document.querySelector('.mq-v080-assignments'))return;parentLoading=true;try{const assignments=await get('/assignments/all');if(!assignments||document.querySelector('.mq-v080-assignments'))return;const section=document.createElement('section');section.className='panel mq-v080-assignments';section.innerHTML=`<div class="mq-v080-head"><div><p class="eyebrow">PRACTICE QUESTS</p><h2>Assign targeted practice</h2></div><span class="mq-pill">v0.8</span></div><form class="mq-assignment-form"><input name="title" placeholder="Practice quest title" value="Targeted practice"><div class="mq-topic-picks">${['number','algebra','measurement','space','statistics','probability'].map(t=>`<label><input type="checkbox" name="topics" value="${t}">${t}</label>`).join('')}</div><label>Questions <input name="count" type="number" min="5" max="50" value="10"></label><label>Due date <input name="due" type="date"></label><button class="primary" type="submit">Assign to Sienna</button></form><div class="mq-assignment-list">${assignments.map((a:any)=>`<article><div><b>${a.title}</b><small>${a.topics.join(', ')} · ${a.question_count} questions${a.due_date?` · due ${a.due_date}`:''}</small></div><span class="status ${a.status}">${a.status.replace('_',' ')}</span></article>`).join('')||'<p class="mq-muted">No practice quests assigned yet.</p>'}</div>`;page.prepend(section);section.querySelector('form')?.addEventListener('submit',async(e:any)=>{e.preventDefault();const f=new FormData(e.target);const topics=f.getAll('topics').map(String);if(!topics.length){alert('Select at least one learning area');return}await post('/assignments',{title:String(f.get('title')||'Practice Quest'),topics,question_count:Number(f.get('count')||10),due_date:String(f.get('due')||'')||null});location.reload()})}finally{parentLoading=false}}

async function enhanceStudentAssignments(){const page=document.querySelector('.page');if(studentLoading||!page||document.querySelector('.mq-v080-student-assignments'))return;studentLoading=true;try{const assignments=await get('/assignments');if(!assignments?.length||document.querySelector('.mq-v080-student-assignments'))return;const section=document.createElement('section');section.className='panel mq-v080-student-assignments';section.innerHTML=`<p class="eyebrow">PARENT PRACTICE</p><h2>Your assigned quests</h2>${assignments.map((a:any)=>`<article><div><b>${a.title}</b><small>${a.question_count} questions · ${a.topics.join(', ')}${a.due_date?` · due ${a.due_date}`:''}</small></div><button data-start-assignment="${a.id}" class="primary">Start practice quest</button></article>`).join('')}`;page.querySelector('.hero')?.insertAdjacentElement('afterend',section);section.querySelectorAll('[data-start-assignment]').forEach((b:any)=>b.addEventListener('click',async()=>{const d=await post(`/assignments/${b.dataset.startAssignment}/start`,{});alert(`${d.question_count}-question practice quest started. Choose ${d.topics.join(', ')} when beginning your next worksheet.`)}))}finally{studentLoading=false}}

function enhance(){renderVisualForCurrent();const text=document.body.textContent||'';if(text.includes('Parent controls')||text.includes('Curriculum coverage'))void enhanceParentAssignments();else void enhanceStudentAssignments()}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('pagehide',()=>observer.disconnect(),{once:true});enhance();
