import './v090.css';

const API='api';
function headers():Record<string,string>{const h:Record<string,string>={'Content-Type':'application/json'};const t=localStorage.getItem('token');if(t)h.Authorization=`Bearer ${t}`;return h}
async function get(path:string){const r=await fetch(API+path,{headers:headers()});return r.ok?r.json():null}
async function post(path:string,body:any={}){const r=await fetch(API+path,{method:'POST',headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Request failed'}))).detail||'Request failed');return r.json()}
let lastAnswer:any=null;
const nativeFetch=window.fetch.bind(window);window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const r=await nativeFetch(input,init);try{const u=String(input);if(/\/api\/questions\/\d+\/answer$/.test(u)&&r.headers.get('content-type')?.includes('json')){lastAnswer=await r.clone().json();setTimeout(enhanceQuestionSupport,50)}}catch{}return r};
function currentQuestion(){const ws=(window as any).__mq_ws;return ws?.questions?.find((q:any)=>q.id===ws.current_question_id)}
function lessonMarkup(d:any){return `<div class="mq-teaching-card"><div class="mq-teaching-title">🧑‍🏫 <div><small>TEACHING MODE</small><h3>${d.title}</h3></div></div>${d.misconception?`<div class="mq-misconception"><b>What MathQuest noticed</b><span>${d.misconception.message}</span></div>`:''}<p>${d.explanation}</p><ol>${d.steps.map((x:string)=>`<li>${x}</li>`).join('')}</ol><div class="mq-example"><b>Worked example</b><span>${d.example}</span></div></div>`}
function enhanceQuestionSupport(){const card=document.querySelector('.question-card');if(!card)return;const q=currentQuestion();if(!q)return;const feedback=card.querySelector('.feedback');if(feedback&&!card.querySelector('.mq-confidence')&&(lastAnswer?.correct||lastAnswer?.retry_allowed===false)){const panel=document.createElement('div');panel.className='mq-confidence';panel.innerHTML='<b>How sure were you?</b><span>This helps MathQuest choose what comes next.</span><div><button data-c="guessed">😕 I guessed</button><button data-c="pretty_sure">🙂 Pretty sure</button><button data-c="knew_it">😎 I knew it</button></div>';feedback.insertAdjacentElement('afterend',panel);panel.querySelectorAll('[data-c]').forEach((b:any)=>b.addEventListener('click',async()=>{await post(`/questions/${q.id}/confidence`,{confidence:b.dataset.c});panel.innerHTML='<b>Thanks!</b><span>MathQuest has adjusted your learning signal.</span>'}))}const needsTeaching=(lastAnswer&&!lastAnswer.correct&&lastAnswer.retry_allowed===false)||(q.hint_count||0)>=2;if(needsTeaching&&!card.querySelector('.mq-teach-button')){const actions=card.querySelector('.question-actions')||card.querySelector('.support-actions');const b=document.createElement('button');b.type='button';b.className='mq-teach-button';b.textContent='🧑‍🏫 Teach me this';b.addEventListener('click',async()=>{b.setAttribute('disabled','true');const d=await get(`/questions/${q.id}/teaching`);if(d){const holder=document.createElement('div');holder.innerHTML=lessonMarkup(d);card.querySelector('.mq-teaching-card')?.remove();card.querySelector('h1')?.insertAdjacentElement('afterend',holder.firstElementChild!)}b.removeAttribute('disabled')});actions?.insertAdjacentElement('beforebegin',b)}}
let masteryLoading=false,adventureLoading=false;
async function addMastery(){const page=document.querySelector('.page');if(masteryLoading||!page||page.querySelector('.mq-v090-mastery'))return;masteryLoading=true;try{const d=await get('/mastery/skills');if(!d?.skills?.length||page.querySelector('.mq-v090-mastery'))return;const top=d.skills.slice(0,8);const section=document.createElement('section');section.className='panel mq-v090-mastery';section.innerHTML=`<div class="mq-v090-head"><div><p class="eyebrow">SKILL-LEVEL MASTERY</p><h2>What is developing next?</h2></div><span class="mq-v090-chip">v0.9</span></div><div class="mq-skill-grid">${top.map((s:any)=>`<article class="${s.status}"><div><b>${s.title}</b><small>${s.code} · ${s.strand}</small></div><strong>${s.mastery}%</strong><span>${s.status.replace('_',' ')}</span></article>`).join('')}</div>`;page.append(section)}finally{masteryLoading=false}}
async function addAdventures(){const page=document.querySelector('.page');if(adventureLoading||!page||page.querySelector('.mq-v090-adventures')||document.body.textContent?.includes('Parent controls'))return;adventureLoading=true;try{const items=await get('/adventures');if(!items?.length||page.querySelector('.mq-v090-adventures'))return;const section=document.createElement('section');section.className='panel mq-v090-adventures';section.innerHTML=`<p class="eyebrow">STORY ADVENTURES</p><h2>Practise maths inside a story</h2><p>Each adventure creates a dedicated themed worksheet while MathQuest still tracks the underlying maths skills.</p><div class="mq-adventure-grid">${items.map((a:any)=>`<button data-theme="${a.id}"><span>${a.icon}</span><b>${a.title}</b><small>${a.intro}</small></button>`).join('')}</div>`;page.querySelector('.hero')?.insertAdjacentElement('afterend',section);section.querySelectorAll('[data-theme]').forEach((b:any)=>b.addEventListener('click',async()=>{const original=b.innerHTML;b.disabled=true;b.textContent='Building your story…';try{const r=await fetch(API+'/worksheets/new',{method:'POST',headers:headers(),body:JSON.stringify({topic:'mixed'})});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Could not create the adventure'}))).detail);const current=await r.json();await post(`/worksheets/${current.id}/adventure`,{theme:b.dataset.theme});sessionStorage.setItem('mq_open_worksheet','1');location.reload()}catch(error:any){b.disabled=false;b.innerHTML=original;alert(error.message)}}))}finally{adventureLoading=false}}
function enhance(){enhanceQuestionSupport();void addMastery();void addAdventures()}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('pagehide',()=>observer.disconnect(),{once:true});enhance();
